# Generated by Django 4.0.5 on 2022-06-22 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Useradmins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('full_name', models.CharField(blank=True, max_length=250, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True, unique=True, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_ip_address', models.CharField(max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('modified_ip_address', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'useradmins',
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('created_on', models.DateTimeField(auto_created=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=255)),
                ('book_image', models.ImageField(default=0, max_length=255, upload_to='books-images/')),
                ('book_author', models.CharField(max_length=255)),
                ('book_publication', models.CharField(max_length=255)),
                ('book_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('block', 'block'), ('delete', 'delete')], default='active', max_length=255)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='book_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, db_column='modified_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'master_books',
            },
        ),
    ]
