# Generated by Django 4.0.5 on 2022-06-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useradmins',
            name='is_superuser',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='useradmins',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
