# Generated by Django 4.0.5 on 2022-06-21 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lmsadmin', '0002_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='book_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='books',
            name='modified_by',
            field=models.ForeignKey(db_column='modified_by', on_delete=django.db.models.deletion.CASCADE, related_name='book_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='books',
            table='master_books',
        ),
    ]
