# Generated by Django 4.0.5 on 2022-06-22 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsadmin', '0003_alter_books_created_by_alter_books_modified_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='book_image',
            field=models.ImageField(default=0, max_length=255, upload_to='books-images/'),
        ),
    ]
