# Generated by Django 4.0.5 on 2022-06-22 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lmsadmin', '0004_books_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='modified_by',
            field=models.ForeignKey(blank=True, db_column='modified_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='books',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
